[package]
org = "wso2"
name = "rfc_as_rest"
version = "0.1.0"
distribution = "2201.9.1"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.sap"
artifactId = "com.sap.conn.idoc"
version="3.1.*"
path="../libs/sapidoc3.jar"

[[platform.java17.dependency]]
groupId = "com.sap"
artifactId = "com.sap.conn.jco"
version="3.1.*"
path="../libs/sapjco3.jar"
